Added Firefox to CircleCI config

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -2,24 +2,32 @@ version: 2
 jobs:
   build:
     docker:
-      - image: ubuntu:16.04
+      - image: circleci/node:12.14.1
     environment:
-      - APP_ID: ipbgaooglppjombmbgebgmaehjkfabme
+      - CHROME_APP_ID: ipbgaooglppjombmbgebgmaehjkfabme
+      - FF_APP_ID: "{15130aad-56df-4f03-9fbd-f91ca1cc658c}"
     steps:
       - checkout
       - run:
           name: "Install Dependencies"
-          command: |
-            apt-get update
-            apt-get -y install curl jq git
+          command: sudo npm i -g web-ext
       - run:
           name: "Package Extension"
-          command: git archive -o automated-bing-searches.zip HEAD:src
+          command: git archive -o package.zip HEAD:src
       - run:
-          name: "Upload & Publish extension to the Google Chrome Store"
+          name: "Upload & Publish Chrome Extension"
           command: |
             if [ "${CIRCLE_BRANCH}" == "master" ]; then
-              ACCESS_TOKEN=$(curl "https://accounts.google.com/o/oauth2/token" -d "client_id=${CLIENT_ID}&client_secret=${CLIENT_SECRET}&refresh_token=${REFRESH_TOKEN}&grant_type=refresh_token&redirect_uri=urn:ietf:wg:oauth:2.0:oob" | jq -r .access_token)
-              curl -H "Authorization: Bearer ${ACCESS_TOKEN}" -H "x-goog-api-version: 2" -X PUT -T automated-bing-searches.zip -v "https://www.googleapis.com/upload/chromewebstore/v1.1/items/${APP_ID}"
-              curl -H "Authorization: Bearer ${ACCESS_TOKEN}" -H "x-goog-api-version: 2" -H "Content-Length: 0" -X POST -v "https://www.googleapis.com/chromewebstore/v1.1/items/${APP_ID}/publish"
+              ACCESS_TOKEN=$(curl "https://accounts.google.com/o/oauth2/token" -d "client_id=${CHROME_CLIENT_ID}&client_secret=${CHROME_CLIENT_SECRET}&refresh_token=${CHROME_REFRESH_TOKEN}&grant_type=refresh_token&redirect_uri=urn:ietf:wg:oauth:2.0:oob" | jq -r .access_token)
+              curl -H "Authorization: Bearer ${ACCESS_TOKEN}" -H "x-goog-api-version: 2" -X PUT -T package.zip -v "https://www.googleapis.com/upload/chromewebstore/v1.1/items/${CHROME_APP_ID}"
+              curl -H "Authorization: Bearer ${ACCESS_TOKEN}" -H "x-goog-api-version: 2" -H "Content-Length: 0" -X POST -v "https://www.googleapis.com/chromewebstore/v1.1/items/${CHROME_APP_ID}/publish"
+            fi
+      - run:
+          name: "Sign & Upload Firefox Addon"
+          # || true so that even when the signing fails for listed addons, the build will not fail
+          # (signing will always fail since the addon will always be pending review)
+          command: |
+            if [ "${CIRCLE_BRANCH}" == "master" ]; then
+              cd src
+              web-ext sign --id="${FF_APP_ID}" --api-key="${FF_JWT_ISSUER}" --api-secret="${FF_JWT_SECRET}" || true
             fi
